# theme.toml template for a Hugo theme

name = "transit_converted"
license = "MIT"
description = ""
homepage = "http://example.de/"
tags = []
features = []
min_version = "0.113.0"

[author]
  name = "Yion"
  homepage = ""

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
